### ISSUE TITLE
Instructions should read 'togglDesc' rather than 'togglDescr'

### ISSUE THREAD

**Issue by selfire1** [evantravers/headspace.spoon#5]
Hi! I have been struggling to get my default descriptions to work and as far as I can tell it's because headspaces parses `togglDesc`. In the instructions `togglDescr` is referenced, hence my descriptions failed to get parsed.

https://github.com/evantravers/Headspace.spoon/blob/09bcc91aedc1f9c05992ea6d64308b1c0def53cd/init.lua#L48

As far as I can tell only `togglDesc` gets processed in the code:

https://github.com/evantravers/Headspace.spoon/blob/09bcc91aedc1f9c05992ea6d64308b1c0def53cd/init.lua#L206

Let me know if I overlooked something and if not, maybe you'd like to remove that confusing 'r' 😀 

Edit: `togglDescr` also appears in the docs:
https://github.com/evantravers/Headspace.spoon/blob/09bcc91aedc1f9c05992ea6d64308b1c0def53cd/docs.json#L26

**Comment by evantravers** [comment]
Great catch! Should be fixed by https://github.com/evantravers/Headspace.spoon/releases/tag/1.1.2
